### ISSUE TITLE
Allow a "curl" one line installation

### ISSUE THREAD

**Issue by seveibar** [seamapi/seam-cli#11]
A lot of packages allow you to install them by pasting a "one-liner" into the terminal with curl, something like `curl https://install.seam.co | sh`. They do this by serving a shell file at the url. How can we create that shell file?

**Comment by seveibar** [comment]
CC @razor-x might know

**Comment by razor-x** [comment]
Is this a single binary with zero dependencies? Does the binary depend on the platform or arch? We need to define what we need to install first before we can script anything.

**Comment by seveibar** [comment]
> Is this a single binary with zero dependencies? Does the binary depend on the platform or arch? We need to define what we need to install first before we can script anything.

It is a single binary

> Is npx an option?

We can't assume users have node installed

**Comment by razor-x** [comment]
> It is a single binary

If this is a single binary that does not require any other system dependencies then we just need to install the binary to the correct path.

> We can't assume users have node installed

It sounds like Node is a requirement then, thus this would NOT be classified as a "single binary."

I am not aware of a good one-line story for Node CLI tools if the user does not have the runtime installed. If that is a critical requirement for this CLI then Go may be a better choice as it optimizes for this use case.

In my experience of using CLI tools in Node, step 1 is always "install Node", and step 2 is "use npx" or `npm i -g". Let me know if you have any example of a Node CLI tool that gets around this or if new tooling exists to assist here. Extreme solutions I have seen will just bundle the runtime, e.g., election apps, or will require Docker instead of Node. 

If requiring the user to install Node first is ok, we can check for that in the script and work from there.

**Comment by seveibar** [comment]
> We can't assume users have node installed

> It sounds like Node is a requirement then, thus this would NOT be classified as a "single binary."

This is a single binary installation. I was emphasizing that we can't assume that the user has node installed (i.e. they can't use npm)

After working with some folks from sales, this is a super safe assumption, configuring their systems was difficult because they needed xcode etc.

**Comment by razor-x** [comment]
Ah ok I misunderstood. It wasn't clear to me that this is bundling the node runtime into the binary.

Then all we need is to download the bin to the "correct location" and set it in the path (more on that in a future comment).

Are we targeting windows users? They would need a different one liner or we would need them to use the windows Linux cli (which I only know of from recent myth)
